language: python
python:
  - "3.6"
# command to install dependencies
install: "sudo apt-get update"
install: "sudo apt-get install apache2"
install: "pip install --upgrade setuptools"
install: "pip install -r requirements.txt"
# command to run tests
script: pytest test/main.py
