language: python
python:
  - "3.6"
  
# command to install dependencies
install: "sudo apt-get install httpd-devel"
install: "pip install --upgrade setuptools"
install: "pip install -r requirements.txt"
# command to run tests
script: pytest test/main.py
