language: python
python:
  - "3.6"
  
before_script:
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  
# command to install dependencies
install: "pip install --upgrade setuptools"
install: "pip install -r requirements.txt"
# command to run tests
script: pytest test/main.py
